### ISSUE TITLE
Problem with some Domains

### ISSUE THREAD

**Issue by PrimeF** [scottbrady91/Python-Email-Verification-Script#1]
Hello,
I've encountered some problems in checking emails with domains like: libero.it, web.de, yahoo.de...
It seems that the script works only with .com addresses.

Could you please help me to solve the issue.

Thanks

**Comment by scottbrady91** [comment]
As stated in the Warnings and Disclaimers section of the accompanying article, this script is purely the basics and will not work with B2C domains such as yahoo or anyone implementing their own custom spam detection rules. The limitation is not on .com domains.

Unfortunately I am currently restricted by an NDA from sharing the requested details, nor do I have any interest in continuing any work in this subject. Sorry that I can't be much help here.

**Comment by PrimeF** [comment]
Ok I understand.
Many Thanks
