### ISSUE TITLE
server.connect(mxRecord) hangs

### ISSUE THREAD

**Issue by ekrolewicz6** [scottbrady91/Python-Email-Verification-Script#6]
First, thanks a ton for this!

My code seems to hang right at the start of the SMTP Converstion:

# SMTP Conversation
server.connect(mxRecord)

I keep quitting and can't seem to understand why its not working. I'm using python2 not python3 (tried it on python3 and got the same issue) but can't imagine that's the issue. I'm not getting an error message it just hangs.

Thanks!

**Comment by scottbrady91** [comment]
Hiya. Thanks for the feedback.

You definitely need to use Python 3 for this.

If you are failing to connect to a mail server it's either them, or you. So, maybe the mail server is accepting your connections, or maybe your machine can't make outbound calls on that port.

**Comment by georgenicholas** [comment]
I've had the same issue.  mxRecord = "ASPMX.L.GOOGLE.COM" never connects with smtplib timing out and reporting "Network is unreachable".  I'm running python 3.6 and dnspython3.

**Comment by mkollek** [comment]
same issue here. Any solutions found yet?
